### ISSUE TITLE
Deliverable 4 conflicting grading rubrics

### ISSUE THREAD

**Issue by xid32** [laboon/CS1632_Summer2018#5]
In the folder 4, there exists a deliverable4.md file and a grading_rubric.txt file. Both two files contains score proportions that  Functionality occupies. In the deliverable4.md file, it states  Functionality occupies 45% of the total score. However, in the grading_rubric.txt file which under the same folder 4, it states Functionality occupies 50% of the total score. Those two grade descriptions are conflicting. In the other word, the instructor should have only one grade rubric or make the descriptions coincident.

**Comment by laboon** [comment]
Correct, I accidentally last left term's rubric up.  Fixed in commit 4c451b10335d1703f63cc3fcd67516bcecd05d2f

Please mark down +1 ISSUE #5 for +1 bonus point on D4.
